connections:
  connection_args:
    GRIDAPPSD_ADDRESS: tcp://gridappsd:61613
    GRIDAPPSD_PASSWORD: manager
    GRIDAPPSD_USER: system
  connection_type: CONNECTION_TYPE_GRIDAPPSD
  id: _E407CBB6-8C8D-9BC9-589C-AB83FBF0826D.5.0
  is_ot_bus: true
